name: Build and Release seatable.tar.gz

on:
  workflow_dispatch:
  release:
    types: [created]
  schedule:
    - cron: '0 2 * * *' # 每天 02:00 执行
      timezone: Asia/Shanghai # 设置时区为中国

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键权限

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Define Docker images
        run: echo "DOCKER_IMAGES=seatable/seatable-python-runner:latest seatable/seatable-developer:latest seatable/seatable-python-starter:latest seatable/seatable-python-scheduler:latest mariadb:10.11 redis:5.0.7" >> $GITHUB_ENV

      - name: Pull Docker images in parallel
        run: |
          echo "Pulling Docker images in parallel..."
          for image in $DOCKER_IMAGES; do
            docker pull $image &
          done
          wait

      - name: Save images to tar.gz
        run: |
          mkdir -p output
          docker save $DOCKER_IMAGES | gzip > output/seatable.tar.gz

      - name: Generate SHA256 checksum
        run: |
          sha256sum output/seatable.tar.gz > output/seatable.tar.gz.sha256

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            output/seatable.tar.gz
            output/seatable.tar.gz.sha256
          tag_name: latest
