name: Build and Release seatable.tar.gz

on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:  # 添加权限
      contents: write

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 拉取镜像
      - name: Pull Docker images
        run: |
          docker pull seatable/seatable-python-runner:latest
          docker pull seatable/seatable-developer:latest
          docker pull seatable/seatable-python-starter:latest
          docker pull seatable/seatable-python-scheduler:latest
          docker pull mariadb:10.11
          docker pull redis:5.0.7

      # 保存镜像到 tar 文件
      - name: Save images to tar.gz
        run: |
          mkdir -p output
          docker save \
            seatable/seatable-python-runner:latest \
            seatable/seatable-developer:latest \
            seatable/seatable-python-starter:latest \
            seatable/seatable-python-scheduler:latest \
            mariadb:10.11 \
            redis:5.0.7 \
            | gzip > output/seatable.tar.gz

      # 上传到 GitHub Releases（使用更可靠的 action）
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: output/seatable.tar.gz  # 自动匹配当前 Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动注入，无需额外配置