name: Build and Release DockerImages

on:
  workflow_dispatch:
  release:
    types: [created]
  schedule:
    - cron: '0 2 * * *'  # 每天 02:00 执行
      timezone: Asia/Shanghai  # 设置时区为中国

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键权限

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yq (YAML parser)
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.16.1/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Load all docker image groups from file
        run: |
          # 读取所有镜像组
          IMAGE_GROUPS=$(yq eval '.image_groups | keys' docker_images.yml | tr -d '[:space:]' | tr '\n' ' ')
          echo "Found image groups: $IMAGE_GROUPS"
          
          # 遍历每个镜像组，单独打包
          for group in $IMAGE_GROUPS; do
            # 获取该组的所有镜像
            IMAGES=$(yq eval ".image_groups.$group[]" docker_images.yml)
            echo "Group $group images: $IMAGES"
            
            # 将镜像名称拼接成一个临时变量
            DOCKER_IMAGES=""

            for image in $IMAGES; do
              DOCKER_IMAGES="$DOCKER_IMAGES $image"
            done
            
            # 根据组名打包并命名文件
            FILENAME="${group}.tar.gz"
            mkdir -p output
            docker save $DOCKER_IMAGES | gzip > output/$FILENAME
            echo "Created $FILENAME"
            
            # 为上传准备 SHA256 校验和文件
            sha256sum output/$FILENAME > output/$FILENAME.sha256
          done

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            output/*.tar.gz
            output/*.tar.gz.sha256
          tag_name: latest
