name: Build and Release seatable.tar.gz

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键权限

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull Docker images
        run: |
          docker pull qwenllm/qwen:latest

      - name: Save images to tar.gz
        run: |
          mkdir -p output
          docker save \
            qwenllm/qwen:latest \
            | gzip > output/qwen.tar.gz

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: output/qwen.tar.gz  # 自动匹配文件名和 Release
          tag_name: latest              # 指定上传到 latest 标签
          overwrite: true               # 覆盖已有的 latest 标签
